// eslint-disable-next-line
const { primaryColor, tabsHorizontalPaddingRight, modalBodyPaddingRight, cardPaddingBase } = require('./defaultSettings')

const theme = {
  'primary-color': primaryColor,
  // 'padding-lg': '18px',
  // 'padding-md': '10px',
  // 'padding-sm': '6px',
  // 'padding-xs': '2px',
  'font-size-base': '13px',
  'font-size-sm': '13px',
  'layout-header-height': '40px',
  // 'form-item-margin-bottom': '0',
  'border-radius-base': '0',
  'border-radius-sm': '0',
  'outline-width': '0',
  // 'btn-height-base': '24px',
  // 'btn-height-lg': '28px',
  // 'btn-height-sm': '24px',
  'control-padding-horizontal': '5px',
  'control-padding-horizontal-sm': '5px',
  // 'input-height-base': '24px',
  // 'input-height-lg': '28px',
  // 'input-height-sm': '24px',
  // 'tabs-vertical-margin': '0px',
  // 'tabs-vertical-padding': '8px 16px',
  'table-header-bg': 'hsv(0, 0, 96%)',
  'modal-header-bg': 'hsv(0, 0, 96%)',
  'modal-body-padding': modalBodyPaddingRight,
  // 'card-head-background': 'hsv(0, 0, 96%)',
  'tabs-card-head-background': 'hsv(0, 0, 96%)',
  // 'tabs-card-height': '28px',
  // 'tabs-bar-margin': '0 0 0 0',
  // 'tabs-horizontal-margin': '0 0 0 0',
  // 'tabs-horizontal-padding': tabsHorizontalPaddingRight,
  // 'tabs-horizontal-padding-sm': tabsHorizontalPaddingRight,
  // 'tabs-views-margin-bottom': '0px',
  // 'tabs-scrolling-size': '28px',
  'radio-button-bg': 'transparent',
  'radio-button-checked-bg': 'transparent',
  'slider-handle-border-width': '1px',
  'slider-handle-color': '#dedede',
  'slider-handle-color-hover': '#dedede',
  'slider-handle-color-focus': '#dedede',
  'slider-handle-color-tooltip-open': '#ddd',
  'slider-handle-color-focus-shadow': 'transparent',
  'slider-handle-shadow': '1px 1px 4px 0 rgba(0,0,0,.13)',
  'progress-radius': '0',
  // 'tabs-card-gutter': '-1px',
  // 'tabs-card-tab-active-border-top': '2px solid @primary-color',
  'basic-layout-pagechildren-content-margin-top': '5px',
  'basic-layout-pagechildren-content-margin': '@basic-layout-pagechildren-content-margin-top',
  'table-selected-row-bg': '#bae7ff',
  'table-padding-vertical': '4px',
  'table-padding-horizontal': '4px',
  'pagination-item-size': '24px',
  // 'card-head-padding': '4px'
  // 'card-inner-head-padding': '8px',
  'card-padding-base': cardPaddingBase,
  'card-head-padding': '4px',
  'card-head-height': '28px',
  'menu-inline-toplevel-item-height': '28px',
  'menu-item-height': '28px',
  'menu-collapsed-width': '60px'
}
module.exports = theme
